<a href="https://colab.research.google.com/github/madanjha/Machine-Learning/blob/main/Encoding_and_Feature_Selection_19thOct_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Encoding and it's type**
When we try to convert the categorical data into numerical.

There are three types of encoding:
1. **Label Encoding**: It converts the categorical data into numerical without any specific order.
2. **Ordinal Encoding**: It Converts the categories into numerical but in passed order (It is useful when we have ordinal data)
3. **One Hot Encoding**: It Creates a new binary columns(two values: 1 or 0) for each category, removing any implied order which makes it suitable for nominal Data

In [ ]:
import pandas as pd
data = {
    "Color":['Red','Blue','Red','Black'] ,
    "Size": ['Large', 'Small','Medium','Large'],
    "Marital Status" : ['Single','Married','Relationship','Single']

}

In [ ]:
data

{'Color': ['Red', 'Blue', 'Red', 'Black'],
 'Size': ['Large', 'Small', 'Medium', 'Large'],
 'Marital Status': ['Single', 'Married', 'Relationship', 'Single']}

In [ ]:
df = pd.DataFrame(data)
df

   Color    Size Marital Status
0    Red   Large         Single
1   Blue   Small        Married
2    Red  Medium   Relationship
3  Black   Large         Single

**Label Encoding** (Follows the alphabetical order)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Color'] = le.fit_transform(df['Color'])
df

   Color    Size Marital Status
0      2   Large         Single
1      1   Small        Married
2      2  Medium   Relationship
3      0   Large         Single

**Ordinal Encoding**

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
'''
small = 0
medium = 1
large = 2
'''

oe = OrdinalEncoder(categories=[['Small','Medium','Large']]) # we are manually defining the order [0,1,2]
df['Size'] = oe.fit_transform(df[['Size']])
df

   Color  Size Marital Status
0      2   2.0         Single
1      1   0.0        Married
2      2   1.0   Relationship
3      0   2.0         Single

**One Hot Encoding**

In [ ]:
df = pd.get_dummies(df,columns=['Marital Status'])
df

,Color,Size,Marital Status_Married,Marital Status_Relationship,Marital Status_Single
0,2,2.0,False,False,True
1,1,0.0,True,False,False
2,2,1.0,False,True,False
3,0,2.0,False,False,True

##**Dimensionality Reduction Technique**
Let say we have a big table of data with many columns where, each column represents differnet informations about something. Sometimes, not all columns are useful.

**Dimensionality Reduction** is the process of reducing the number of columns while keeping the important information. It help us to do calculation faster and also makes model simpler so that we can get increased accuracy

**There are Two approches we can follow**
###**1. Feature Selection**
Feature Selection is like picking the most important columns from the table and ignoring the rest.
* **VIF (Variance Inflation Factor)**: Helps remove features that are very similar to each other (multicolinearity). so that our model does not get confused.
* **RFE (Recursive Feature Elimination)**: It tests features one by one to see which are the most important and removes the less usefull ones.

###**2. Feature Extraction**
It is a technique to create new features by combining or transforming the exisitng ones. Instead of just picking columns, it makes new columns that summarize the original data.
* **PCA (Principal Component Analysis)**: It Combines the column into fewer new ones that capture the most information
* **LDA (Linear Discriminant Analysis)**: It creates new features to better seperate different groups in the data.

**Conclusion**

Both Reduces dimensions and make data easuer to work with and model more effiecient

In [ ]:
import numpy as np
df = pd.read_csv('/content/bank-additional-full.csv',sep=';')
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56.0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57.0,services,married,high.school,unknown,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37.0,services,married,high.school,no,yes,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40.0,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56.0,services,married,high.school,no,no,yes,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41194,74.0,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41195,74.0,NaN,married,professional.course,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41196,74.0,retired,married,NaN,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41198,74.0,retired,married,professional.course,no,yes,NaN,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,NaN,-50.8,1.028,4963.6,no

**Let's implement VIF**

**We first drop all the null values**

In [ ]:
df.isnull().sum()

age               4
job               5
marital           5
education         5
default           4
housing           3
loan              4
contact           4
month             3
day_of_week       3
duration          3
campaign          3
pdays             3
previous          3
poutcome          5
emp.var.rate      3
cons.price.idx    4
cons.conf.idx     3
euribor3m         3
nr.employed       3
y                 3
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

**Now if we have to select all numerical columns**

In [ ]:
numericCols = df.select_dtypes(include=np.number)
numericCols

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,56.0,261.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0
1,57.0,149.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0
2,37.0,226.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0
3,40.0,151.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0
4,56.0,307.0,1.0,999.0,0.0,1.1,93.994,-36.4,4.857,5191.0
...,...,...,...,...,...,...,...,...,...,...
41185,56.0,189.0,2.0,999.0,0.0,-1.1,94.767,-50.8,1.028,4963.6
41186,44.0,442.0,1.0,999.0,0.0,-1.1,94.767,-50.8,1.028,4963.6
41187,74.0,239.0,3.0,999.0,1.0,-1.1,94.767,-50.8,1.028,4963.6
41193,94.0,239.0,3.0,999.0,1.0,-1.1,94.767,-50.8,1.028,4963.6
41194,74.0,239.0,3.0,999.0,1.0,-1.1,94.767,-50.8,1.028,4963.6

**Finally We will implement VIF**

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

In [ ]:
thresh = 5

while True:
  vifData = pd.DataFrame()
  vifData['Feature'] = numericCols.columns
  vifData['VIF'] = [vif(numericCols.values, i) for i in range(len(numericCols.columns))]
  max_vif = vifData['VIF'].max()
  if max_vif > thresh:
    max_feature = vifData.loc[vifData['VIF'].idxmax(),'Feature']
    print(f'Removing {max_feature} with vif = {max_vif:.2f}')
    numericCols = numericCols.drop(columns = [max_feature])
  else:
    break


print(f'Final Feature with acceptable VIF')
vifData

Removing nr.employed with vif = 26717.53
Removing cons.price.idx with vif = 301.06
Removing euribor3m with vif = 54.17
Removing cons.conf.idx with vif = 39.33
Removing pdays with vif = 11.83
Final Feature with acceptable VIF

        Feature       VIF
0           age  2.806447
1      duration  1.876223
2      campaign  1.807339
3      previous  1.357278
4  emp.var.rate  1.238989

In [ ]:
numericCols.columns

Index(['age', 'duration', 'campaign', 'previous', 'emp.var.rate'], dtype='object')

In [ ]:
df.drop(columns='nr.employed',axis=1)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,y
0,56.0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261.0,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,no
1,57.0,services,married,high.school,unknown,no,no,telephone,may,mon,149.0,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,no
2,37.0,services,married,high.school,no,yes,no,telephone,may,mon,226.0,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,no
3,40.0,admin.,married,basic.6y,no,no,no,telephone,may,mon,151.0,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,no
4,56.0,services,married,high.school,no,no,yes,telephone,may,mon,307.0,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41185,56.0,retired,married,university.degree,no,yes,no,cellular,nov,fri,189.0,2.0,999.0,0.0,nonexistent,-1.1,94.767,-50.8,1.028,no
41186,44.0,technician,married,professional.course,no,no,no,cellular,nov,fri,442.0,1.0,999.0,0.0,nonexistent,-1.1,94.767,-50.8,1.028,yes
41187,74.0,retired,married,professional.course,no,yes,no,cellular,nov,fri,239.0,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,no
41193,94.0,retired,married,professional.course,no,yes,no,cellular,nov,fri,239.0,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,no
41194,74.0,retired,married,professional.course,no,yes,no,cellular,nov,fri,239.0,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,no

**Implementaion of RFE**

In [ ]:
import numpy as np
df = pd.read_csv('/content/bank-additional-full.csv',sep=';')
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56.0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57.0,services,married,high.school,unknown,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37.0,services,married,high.school,no,yes,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40.0,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56.0,services,married,high.school,no,no,yes,telephone,may,mon,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41194,74.0,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41195,74.0,NaN,married,professional.course,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41196,74.0,retired,married,NaN,no,yes,no,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,94.767,-50.8,1.028,4963.6,no
41197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41198,74.0,retired,married,professional.course,no,yes,NaN,cellular,nov,fri,...,3.0,999.0,1.0,failure,-1.1,NaN,-50.8,1.028,4963.6,no

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

**We need to encode first to pass the data**

In [ ]:
le = LabelEncoder()
for i in df.columns:
  if df[i].dtypes == 'object':
    df[i] = le.fit_transform(df[i])

In [ ]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56.0,3,1,0,0,0,0,1,6,1,...,1.0,999.0,0.0,1,1.1,93.994,-36.4,4.857,5191.0,0
1,57.0,7,1,3,1,0,0,1,6,1,...,1.0,999.0,0.0,1,1.1,93.994,-36.4,4.857,5191.0,0
2,37.0,7,1,3,0,2,0,1,6,1,...,1.0,999.0,0.0,1,1.1,93.994,-36.4,4.857,5191.0,0
3,40.0,0,1,1,0,0,0,1,6,1,...,1.0,999.0,0.0,1,1.1,93.994,-36.4,4.857,5191.0,0
4,56.0,7,1,3,0,0,2,1,6,1,...,1.0,999.0,0.0,1,1.1,93.994,-36.4,4.857,5191.0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41177 entries, 0 to 41193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41177 non-null  float64
 1   job             41177 non-null  int64
 2   marital         41177 non-null  int64
 3   education       41177 non-null  int64
 4   default         41177 non-null  int64
 5   housing         41177 non-null  int64
 6   loan            41177 non-null  int64
 7   contact         41177 non-null  int64
 8   month           41177 non-null  int64
 9   day_of_week     41177 non-null  int64
 10  duration        41177 non-null  float64
 11  campaign        41177 non-null  float64
 12  pdays           41177 non-null  float64
 13  previous        41177 non-null  float64
 14  poutcome        41177 non-null  int64
 15  emp.var.rate    41177 non-null  float64
 16  cons.price.idx  41177 non-null  float64
 17  cons.conf.idx   41177 non-null  float64
 18  euribor3m       41177 non-null  float64
 19  nr.employed     41177 non-null  float64
 20  y               41177 non-null  int64
dtypes: float64(10), int64(11)
memory usage: 6.9 MB

**Now let's start building model for RFE**

In [ ]:
x = df.drop("y",axis= 1)
y = df['y']

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
rfe = RFE(model) # passing the model inside rfe to apply RFE on it
rfe.fit(x,y)

RFE(estimator=LogisticRegression())

**RFE will give us the index of columns that are important**

In [ ]:
select_index =  [i for i, data in enumerate(rfe.support_) if data == True]

**Store the column name in a list**

In [ ]:
column_name = x.columns

In [ ]:
selected_column_names = [column_name[i] for i in select_index]
selected_column_names

['marital',
 'default',
 'contact',
 'month',
 'day_of_week',
 'campaign',
 'previous',
 'poutcome',
 'cons.conf.idx',
 'euribor3m']

Now we will select the columns and check the scores

In [ ]:
x = df.loc[:,['marital',
 'default',
 'contact',
 'month',
 'day_of_week',
 'campaign',
 'previous',
 'poutcome',
 'cons.conf.idx',
 'euribor3m']]

y = df['y']

Data splitting into train and test set

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [ ]:
x_train.shape

(32941, 10)

In [ ]:
x_test.shape

(8236, 10)

**Now the model will use for prediction**

In [ ]:
LogReg = LogisticRegression()

In [ ]:
LogReg.fit(x_train,y_train)

LogisticRegression()

**Test our Model**

In [ ]:
y_pred = LogReg.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import *

In [ ]:
print(f'Accuracy score of Model After applying RFE: {accuracy_score(y_pred,y_test)*100:.2f}%')

Accuracy score of Model After applying RFE: 89.16%

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.99      0.90      0.94      7997
           1       0.17      0.69      0.27       239

    accuracy                           0.89      8236
   macro avg       0.58      0.79      0.61      8236
weighted avg       0.97      0.89      0.92      8236

We will now save our model

In [ ]:
import joblib
joblib.dump(LogReg,'LogModel.pkl')

['LogModel.pkl']

In [ ]:
new_data = pd.DataFrame(x.iloc[2])

In [ ]:
new_data

                    2
marital         1.000
default         0.000
contact         1.000
month           6.000
day_of_week     1.000
campaign        1.000
previous        0.000
poutcome        1.000
cons.conf.idx -36.400
euribor3m       4.857

In [ ]:
new_pred = LogReg.predict(new_data.T) # The reason why we did transpose -> I want 1 row and 10 columns for my model
new_pred

array([0])

##**Gradio**

In [ ]:
import gradio as gr

In [ ]:
x.columns

Index(['marital', 'default', 'contact', 'month', 'day_of_week', 'campaign',
       'previous', 'poutcome', 'cons.conf.idx', 'euribor3m'],
      dtype='object')

In [ ]:
def predictFunc(*args):
  data_dict = {col: [val] for col,val in zip(x.columns,args)}
  input_data = pd.DataFrame(data_dict)

  pred = LogReg.predict(input_data)[0]
  prob = LogReg.predict_proba(input_data)[0][1]

  return f'Prediction : {"Yes" if  pred ==1 else "No"} (probabilty of "Yes" = {prob:.2f})'

In [ ]:
new_data.T.values

array([[  1.   ,   0.   ,   1.   ,   6.   ,   1.   ,   1.   ,   0.   ,
          1.   , -36.4  ,   4.857]])

In [ ]:
predictFunc(*new_data.T.values[0])

'Prediction : No (probabilty of "Yes" = 0.04)'

In [ ]:
x.columns

Index(['marital', 'default', 'contact', 'month', 'day_of_week', 'campaign',
       'previous', 'poutcome', 'cons.conf.idx', 'euribor3m'],
      dtype='object')

In [ ]:
input = [
    gr.Number(label='marital'),
    gr.Number(label='default'),
    gr.Number(label='contact'),
    gr.Number(label='month'),
    gr.Number(label='day_of_week'),
    gr.Number(label='campaign'),
    gr.Number(label='previous'),
    gr.Number(label='poutcome'),
    gr.Number(label='cons.conf.idx'),
    gr.Number(label='euribor3m'),
]

**We will create gradio interface**

In [ ]:
interface = gr.Interface(
    fn = predictFunc,
    inputs = input,
    outputs = gr.Textbox(label = "Result"),
    title = "BanK Marketing Prediction App",
    description = 'Please enter the values to check whether customer will subscribe (Yes/No)'
)

In [ ]:
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://2c0ddf124994ce3001.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)